name: 'Build'
description: 'Build app from dockerfile'
inputs:
  aws-access-key-id:  # id of input
    description: 'AWS_ACCESS_KEY_ID'
    required: true
  aws-secret-access-key:  # id of input
    description: 'AWS_SECRET_ACCESS_KEY'
    required: true
# outputs:
#   random-number:
#     description: "Random number"
#     value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    ## Clone do código
    - name: Check out code
      uses: actions/checkout@v2
    
    ## Configurando as credenciais AWS
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: sa-east-1
        mask-aws-account-id: 'no'